### ISSUE TITLE
Questions regarding the project

### ISSUE THREAD

**Issue by Glitchy-Tozier** [grasegger/klo#1]
Hi, i just found your project through random chance. I'm interested, and would like to ask some questions.

Am I correct in assuming this is going to be a Rust version of [Arnes keyboard optimizer](https://hg.sr.ht/~arnebab/evolve-keyboard-layout/)? Looking at the Neo-layout in the .json and the very similar structure, i was very intrigued!

(Especially since I also made strides to improving upon that script)

**Comment by grasegger** [comment]
Hi @Glitchy-Tozier, 

exactly, a yet to be written README will explain that (and differences) in the future. It's quite early stage and not yet usable. :)

**Comment by Glitchy-Tozier** [comment]
Thank you for the quick reply!  :)

Could you explain to me what you're planning to do?
As mentioned in [my project](https://github.com/Glitchy-Tozier/Revolve-keyboard-layout) at the beginning of the README, I'm looking for a less cluttered version of Arne's Script.

> It's quite early stage and not yet usable.

I know, I tried it out ;)

A few questions:
- Do you plan on adding all of that functionality he created? Or do you plan on focusing on one path for optimizing layouts?
- Do you intend to use the same criteria as he did?
- Do you speak German?

**Comment by grasegger** [comment]
I guess the first milestone is to generate layouts with the default settings of the original project. I've skipped a few steps here and there and I know that my bigram logic is different right now. 

The big plan is to provide a faster way to generate layouts. I wanted to do this the same way the original logic does. 

Later I wanted to add logic that allows to provide your own scripts for cost calculation (maybe with some DSL which only gets parsed once, not sure yet) and other parts. 

Ja, ich spreche deutsch.

**Comment by Glitchy-Tozier** [comment]
Understood, sounds good to me!

Are you open to me helping out (Contributing code)? It'll probably be pretty slow in the beginning because this would be my first time writing Rust, but it'll probably speed up quickly. I'm motivated to finally create a good NEO-like layout-optimizer.

The good thing is that over the last few days, I've come to be pretty familiar with the main parts of Arne's script.

Passt, ich auch. Ich nehme aber an, du möchtest bei Englisch bleiben, so wie das Projekt aussieht. Find ich eh besser, wenn es auch für andere Sprachen verständlich ist. :)

**Comment by grasegger** [comment]
Any help is welcome, just create a pull request. It doesn't need to be a finished feature, I can provide help and feedback in a PR. :)

Also I enabled discussions for a more free form talk about the project, so we can plan and organize there and focus on tasks within the issues. 

The german optimizers are actually used by a lot of english speaking folks already, which is why I've choosen to stick to english.
